### PR TITLE
Added support for fieldsets and fixed inheritance issue.

### PR DESCRIPTION
**Pull request by farooqaaa**
I tried to inherit the Config model and changed the app_label but it wasn't working because Config was hard-referenced here. Used self.model instead.

Also, putting all the settings in one table makes it hard to group relation options so I have added support for fieldsets.

### CODE REVIEW

**Comment by camilonova** [comment]
Looks beautiful. Can you please add documentation on how to use the fieldsets?

**Comment by farooqaaa** [comment]
Sorry about that! I forgot to document that. It's pretty simple:

```
CONSTANCE_CONFIG : {
    'SITE_NAME': ('My Title', 'Website title'),
    'SITE_DESCRIPTION': ('', 'Website description'),
    ...
}

CONSTANCE_CONFIG_FIELDSETS = {
    'General Options': ['SITE_NAME', 'SITE_DESCRIPTION'],
    'Theme Options': ['BACKGROUND_COLOR', 'THEME'],
}
```

**Comment by camilonova** [comment]
Thank you

**Comment by sobolevn** [comment]
Is it going to be released anytime soon?

**Comment by camilonova** [comment]
@sobolevn just released a new version.

**Pull request merged**
