### PR TITLE
Don't call backend.set when backend.get returns None and default value is None

### PR DESCRIPTION
**Pull request by i2xS**
Hi there!

**Preconditions:** 
Any constance variable 
default value: None
current value: None

Reading value through config.VALUE_NAME leads to backend.set('VALUE_NAME', None) call, which updates None to None.

This behaviour led us to database failure on production when 80 simultaneous value reads happen, which eventually led to  simultaneous writes and deadlocks. Deadlocks led to service restarts, emitting new connections to database and new deadlocks.

### CODE REVIEW

**Review by Mogost — APPROVED** [review]

**Review by jezdez — CHANGES_REQUESTED** [review]
Please provide a test case to make sure this won't break again.

**Comment by camilonova** [comment]
@i2xS should we close this one?

**Comment by MichaelDanielTom** [comment]
Any reason not to merge this? Seems like this should be the desired behavior, and it's still relevant given [this](https://github.com/jazzband/django-constance/issues/348).

**Comment by camilonova** [comment]
@i2xS @MichaelDanielTom can you provide a test so we can merge this?

**Pull request closed without merging**
