### PR TITLE
Make CONSTANCE_ADDITIONAL_FIELDS more flexible

### PR DESCRIPTION
**Pull request by therefromhere**
Allow the field config to be a tuple, and allow the config dict to be omitted.

### CODE REVIEW

**Comment by camilonova** [comment]
Can you please document it better?

**Comment by therefromhere** [comment]
Do you mean in `docs/index.rst`? Yep, will do.

**Comment by therefromhere** [comment]
@camilonova done

**Comment by vamsi** [comment]
@camilonova I think the pr can be merged.

**Comment by camilonova** [comment]
Thank you

**Pull request merged**
