### PR TITLE
Add DummyBackend.

### PR DESCRIPTION
**Pull request by POD666**
It was useful for my case.
I will also add some notes to docs if you like it.

### CODE REVIEW

**Comment by jezdez** [comment]
Can you elaborate what the use case for this is?

**Comment by POD666** [comment]
In my case django-constance is used for staging environment only - it gives the ability to change settings for QA.
DummyBackend works faster in production.

**Comment by camilonova** [comment]
I don't see this is a fit for the project.

I know there are ways to mock the redis connection for testing. I'll see if I can find it.

**Comment by camilonova** [comment]
Thank you. I'll close this in favor of keeping the scope of the project as simple as possible.

**Pull request closed without merging**
