### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by Mogost**
I think we all did a good job and deserve a new release.

### CODE REVIEW

**Comment by david-griffiths-eigen** [comment]
How close is this version from being released. The In-memory backend is already in the documentation...

**Comment by Mogost** [comment]
@jezdez can we do something to make the release faster?
I once again reviewed all changes point-by-point.
<details>
<summary>Tested or safe changes</summary>
Safely remove obsolete code
- [x] Delete south migrations

Not Functional Changes (docs/examples/setup.cfg)
- [x] Improve grammar of documentation index file
- [x] Simplify documentation installation section
- [x] Update example project for Django>2 
- [x] Put back wheel generation in travis

Changes I personally verified
- [x] Fix IntegrityError after 2.5.0 release (Allow concurrent calls to `DatabaseBackend.set()` method)
- [x] Fix wrong "is modified" in admin for multi line strings
- [x] Added a sticky footer in django constance admin
- [x] Add anchors in admin for constance settings
- [x] Make constance app verbose name translatable
- [x] Fix Attempts to change config values fail silently and appear to succeed when user does not have change permissions
- [x] Make groups of fieldsets collapsable

Affects only tests
- [x] Allow override_config for pytest
- [x] Add memory backend
</details>

Changes that are doubtful or unverified
- [ ] [Switch md5 to sha256](https://github.com/jazzband/django-constance/pull/395) 
_(I just do not understand these changes and whether they can have any negative effect.)_

**Comment by camilonova** [comment]
Merged in 96e95fcfe61c3486fa6ad4dbec136d9f7b9b423f

**Comment by david-griffiths-eigen** [comment]
Thanks guys! Appreciate your efforts :+1:

**Pull request closed without merging**
