### PR TITLE
Allow to override field config_type and set custom additional fields

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
The Travis is failing, but I can't see the error. Can somebody point me, what is the fault?

**Comment by PetrDlouhy** [comment]
This is answer to comment under PR #46.

Hi @bufke, thanks very much for your answer.

This new PR doesn't contain any translation (it has been commited by somebody else anyway). It is the custom additional fields fuctionality only. I used a new approach, which seems cleaner to me.

I can make my own project fork, but I think it would lead to redundant effort, wasted potential and fragmented attention of users. If there is some help needed, I would rather help with original project, than the forked one.

**Comment by PetrDlouhy** [comment]
Hi all, @jezdez,

I have corrected merge errors with current Django constance version. The Travis tests are passing now.

I am still interested in merging my changes into main repository. I can even help with maintaining this project.

**Comment by camilonova** [comment]
@PetrDlouhy Thank you.

**Pull request merged**
