### PR TITLE
Feature/logentry

### PR DESCRIPTION
**Pull request by mavriq**
Hi, I added the ability to enable logging of constant changes.
I hope you find this useful.

### CODE REVIEW

**Comment by camilonova** [comment]
I'm not seeing this into the scope of this library.

**Comment by mavriq** [comment]
In this case, tell me how best to do?
Should I fork this project? or can I enable logging of changes with the current library?
I see that the same request was in the past from other users #19

**Comment by jezdez** [comment]
@mavriq Constance provides a [`config_updated` signal](https://django-constance.readthedocs.io/en/latest/#signals) that you can use to log changes. Signal receivers get both the old and the new value. The Django docs provide help how to [listen to signals](https://docs.djangoproject.com/en/2.2/topics/signals/#listening-to-signals).

I'm closing this PR for now since it's clearly a no-go.

**Comment by Anton-Shutik** [comment]
@jezdez There are at least several people who would like to see such an option in the app. Some of them even provided a solution like this. Why not to merge it ? You can say: go ahead and fork, but I'm not a fun of doing this as well as a lot of other developers.

 @mavriq spent and "hour" making this PR, which might save this "hour" for hundreds of other developers who are using the app. Isn't it what opensource is great for ?

>Thank you. I'm not seeing this into the scope of this library.

@camilonova Totally disagree. That would be a great feature of this library.

PS.
Ready to help with implementing the feature.
Related issue https://github.com/jazzband/django-constance/issues/19

**Comment by jezdez** [comment]
@Anton-Shutik The feature request was deemed out of scope of this app (read: the amount of time needed to maintain it outweighs the expected usefulness), so it doesn't matter if it was requested by many people, especially since there are alternatives.

The feature idea isn't bad of course, I mentioned that there is a relatively easy way to do this using the `config_updated` signal which is a low-maintenance-cost way to provide an official API to receive updates when a Constance config value changes.

Connecting a signal callback function to that signal to log the changes in a app-specific data model (or whatever logging mechanism is useful for your application) is simply left to the user of the app. This is a very common trade-off for edge case features in libraries such as Constance.

I'd like to encourage you to try implementing this in your project instead, or maybe write a blog post how to connect `config_updated` and the Django admin log facility. Good luck!

**Comment by Anton-Shutik** [comment]
>The feature idea isn't bad of course, I mentioned that there is a relatively easy way to do this using the config_updated signal which is a low-maintenance-cost way to provide an official API to receive updates when a Constance config value changes.

Yep, that's why people would like to have that implemented as option in this app, rather then implementing in their project. Note that each dev have to implement it instead of being done once in the app and reused.

>I'd like to encourage you to try implementing this in your project instead, or maybe write a blog post how to connect config_updated and the Django admin log facility. Good luck!

That might be a good idea, but I think it won't have enough features to be considered as separate project, since it will closely related to constance.

**Comment by jezdez** [comment]
> > The feature idea isn't bad of course, I mentioned that there is a relatively easy way to do this using the config_updated signal which is a low-maintenance-cost way to provide an official API to receive updates when a Constance config value changes.
> 
> Yep, that's why people would like to have that implemented as option in this app, rather then implementing in their project. Note that each dev have to implement it instead of being done once in the app and reused.

No, the existence of a developer API like a Django signal isn't a reason to implement a very specific feature in the library providing that API. That's just not what those things are there for. I know that you want this feature, but without investing time in maintaining it yourself. Which means we are at an impasse, having to agree to disagree.

> > I'd like to encourage you to try implementing this in your project instead, or maybe write a blog post how to connect config_updated and the Django admin log facility. Good luck!
> 
> That might be a good idea, but I think it won't have enough features to be considered as separate project, since it will closely related to constance.

You don't know until you try, a full-blown project may not be needed but instead a snippet somewhere, or simply a blog post titled "How to integrate django-constance with the Django admin to create an audit log".

**Comment by Anton-Shutik** [comment]
I would not say that this is very specific feature. I can agree that a lot of (or even most of ) developers won't need it, but likely would use it if it exists. This is kinda "nice-to-have" feature. 

I didn't say that I want this feature without investing time in maintaining it myself. This is not true. I just said that once implemented it would save a bunch of time for other people.

I've added a [draft PR](https://github.com/jazzband/django-constance/pull/336), that adds the feature optionally. That might be helpful for other devs.

**Comment by jezdez** [comment]
Thanks for opening the PR, this will be useful for others to implement it on their own. I've closed the PR as to not falsely suggest that it'll be merged. The feature continues to be out of scope of django-constance.

**Pull request closed without merging**
