### PR TITLE
Collections support

### LINKED ISSUE #574: Add support for collection types (list/tuple/dict/set/etc.)
### Describe the problem

Using the `DatabaseBackend`, I store lists of recipients for emails and dicts for small configy-things. The (awesome) changes in https://github.com/jazzband/django-constance/pull/564 do not cover these types. The stored value in the database is not in the expected format
```
'{"__type__": "default", "__value__": "{"test": "test"}"}'
```
but 
```
'{"test": "test"}'
```

This then leads to an exception when trying to access the value, as the keys do not match the expected structure (https://github.com/jazzband/django-constance/blob/master/constance/codecs.py#L58).

**Proposed discussion**

I could help out with any of the following tasks:

* [ ] treat the defined types (https://github.com/jazzband/django-constance/blob/master/constance/codecs.py#L37 and https://github.com/jazzband/django-constance/blob/master/constance/codecs.py#L83) as "whitelist" and raise on serialization of unknown types.
* [ ] document the supported types, or indicate the internal wokings. A simple sentence indicating usage of JSON as data structure would probably be good enough.
* [ ] try to deserialize the object (https://github.com/jazzband/django-constance/blob/master/constance/codecs.py#L57) with the default JSONSerializer before raising an exception. This might be helpful if other users face the same issue and have already-migrated data.
* [ ] probably out of scope: use the registered types for nested serialization (e.g. a dict with a UUID).
 
### Steps to reproduce

This simply uses the default encoding defined in the `JSONEncoder`, but should display the issue clearly 😄 
See https://github.com/jazzband/django-constance/compare/master...sebastianmanger:django-constance:json-missing-types

### System configuration

* Django version: any
* Python version: any
* Django-Constance version: >4.0.0

### PR DESCRIPTION
**Pull request by Mogost**
Fix #574

@sebastianmanger @lpomfrey This PR should address your problem from #574, could you please review/test it?

cc: @ivan-klass @Natim @camilonova

### CODE REVIEW

**Comment by lpomfrey** [comment]
We've done some testing and this would seem to fix our problems from #574 :+1:

**Review by camilonova — APPROVED** [review]

**Comment by camilonova** [comment]
Looks good to me

**Comment by Mogost** [comment]
There's a lack of documentation. If anyone has time to help with it, I would be glad!

**Comment by sebastianmanger** [comment]
Thanks a lot! This fully supports "my" use cases.
As a "pure" user of the library, I personally would expect something minimal like https://github.com/sebastianmanger/django-constance/commit/7c24c6de576e29eaf8aa9b2f449331bc1ecea3e0

**Comment by Mogost** [comment]
> Thanks a lot! This fully supports my use cases. As a pure user of the library, I personally would expect something minimal like [sebastianmanger@7c24c6d](https://github.com/sebastianmanger/django-constance/commit/7c24c6de576e29eaf8aa9b2f449331bc1ecea3e0)

Thank you. cherry-picked

**Comment by Mogost** [comment]
Tagged with 4.1.0 version. Should be released soon

**Pull request merged**
