### PR TITLE
Add anchors in admin

### PR DESCRIPTION
**Pull request by Mogost**
Very often there is a need to provide links to a specific setting, anchors would be very useful.
image

### CODE REVIEW

**Comment by jezdez** [comment]
I really like the idea but visually this can be improved, maybe by just using the item name as the link text instead of adding the extra character.

**Comment by Mogost** [comment]
@jezdez 
I originally did so, but I didn’t like that the whole title behaves like a link. This is reflected in colors, etc. In general, ideally, we need to add some more css so that the symbol is shown exclusively when you hover over the inscription. An example of this behavior is in github.
image

**Comment by jezdez** [comment]
Yeah, fair point, let's do the hover idea.

**Comment by Mogost** [comment]
@jezdez done

**Comment by jezdez** [comment]
Could you add a new screenshot please?

**Comment by jezdez** [comment]
Or has this not changed visually other than the hover effect?

**Comment by Mogost** [comment]
image
on hover
image
I tried this on my project, at first glance it works well and copes equally well with both long and short variable names.
In the worst case scenario, if I did not take something into account, this will not lead to critical consequences and we will be informed about this in issues.

**Comment by Mogost** [comment]
@jezdez I have also been waiting for a new release for a very long time. I'm still using 2.4.0 in my project because #383 affected me.

**Pull request merged**
